### PR TITLE
Codeunit to handle reading and writing record link notes

### PR DESCRIPTION
**Pull request by gunnargestsson**
We need to be able to read and write notes for NAV records.
Now adding unit test :)

### CODE REVIEW

**Comment by gunnargestsson** [comment]
Added changes to COD1290 and a test codeunit 50060.  Wanted to update JwtSecurityToken handling

**Comment by JesperSchulz** [comment]
It appears you are mixing two different pull requests together? This one is about "Codeunit to handle reading and writing record link notes". Please do not address changes for COD1290 in this pull request, as it makes it very hard figure out what is going on. If you have changes to COD1290, please create a new pull request and explain the requested changes :-) Thank you!

**Comment by gunnargestsson** [comment]
I need to figure out how to do that...  two pull requests...

**Comment by gunnargestsson** [comment]
If I add new files to my fork it just gets automatically added to the open pull request.

**Comment by JesperSchulz** [comment]
Git does have a quite steep learning curve, yes :) I would recommend a short tutorial. Just google it!
Pull requests are based on branches. You need to create a new branch, if you want to create a new pull request. That's the short version! Hope you figure it out!

**Comment by gunnargestsson** [comment]
I did what you asked and you have a new pull request :)

**Comment by JesperSchulz** [comment]
Perfect! I'll look into it when time allows :) Thank you!

**Comment by JesperSchulz** [comment]
There are still some changes to COD 1290. Those do not belong in this pull request, do they? Anyway, we'll manage :)

**Comment by gunnargestsson** [comment]
Correct, ignore changes to COD 1290

**Comment by JesperSchulz** [comment]
After taking a closer look, I believe your AddNote functionality can be covered by calling COD10's function WriteRecordLinkNote. I will add a similar function to COD10 for Reading. Stay tuned.

**Comment by JesperSchulz** [comment]
ReadRecordLinkNote function added through pull request #16. This should suffice to achieve the functionality requested. If not, please comment and reopen this pull request. And again, thank you for enriching our application with your useful additions!

**Pull request closed without merging**
