### PR TITLE
Need information from the system permission into my AL app.  

### PR DESCRIPTION
**Pull request by gunnargestsson**
Permission Table is not visible to the AL app and I need to ask if a user has access to a specific table by default in the system.
New code is the function 

PROCEDURE GetTablePermissionFromApplication@29(TableId@1000 : Integer;VAR TablePermissionBuffer@1001 : Record 9800);

### CODE REVIEW

**Comment by PredragMaricic** [comment]
Hey Gunnar,
Why can't we use READPERMISSION or WRITEPERMISSION in this case? What exactly is advantage if we use your function?
Thanks for your contribution,
Predrag

**Comment by gunnargestsson** [comment]
I could do that in most cases but this is more detailed.  For example the WRITEPERMISSION needs both Insert and Modify to return true - if I remember correctly.

**Comment by gunnargestsson** [comment]
We now have direct access to Permission table from AL.  Not needed any more.

**Comment by PredragMaricic** [comment]
Agree. Thanks for suggestion.

**Pull request closed without merging**
