### PR TITLE
New functions for Type Helper

### PR DESCRIPTION
**Pull request by gunnargestsson**
FormatDecimal (dot net formatting)
FormatUtcDateTime (dot net formatting)
ConvertToAscii (convert accent characters)

### CODE REVIEW

**Comment by JesperSchulz** [comment]
Time to get some traction on this request. But first I need clarification on your ASCII function. It looks awfully much like the function we have in COD47 - StringConversionManagement. How does your implementation differ? I would hate to have two parallel implementations for the same thing. If COD47 doesn't fit your needs, maybe we should try to fix that one instead?

**Comment by gunnargestsson** [comment]
You are correct.  Let's use the COD47 function and don't implement ConvertToAscii.
My bad...

**Comment by JesperSchulz** [comment]
:-) OK! I'll move forward with the other two functions then! Sorry it took me so long...

**Comment by JesperSchulz** [comment]
Request addressed though commit a299dbcbe828dbc90f24299bb94382d49d43da13. If you don't agree with the solution, please re-open pull request. But I think it should be alright :-)

**Pull request closed without merging**
