### PR TITLE
Zip Stream Wrappers

### PR DESCRIPTION
**Pull request by anzwdev**
Zip stream wrapper codeunit to compress and uncompress zip files using nav streams

### CODE REVIEW

**Comment by JesperSchulz** [comment]
Thank you for your contribution! I will look into the request before EOW and get back to you, if I have any questions or comments. On first look, everything looks fine, and seeing that we currently only have AddStreamToZipStream in COD419, I believe we are lacking some of this functionality.

**Comment by anzwdev** [comment]
I've created it as a separate codeunit, because i wanted to store zip memory stream inside and create or open zip only once during whole processing. AddStreamToZipStream function in COD419 is stateless which means that it opens and closes zip each time you want to add a new file to it.

**Comment by JesperSchulz** [comment]
Sounds reasonable. I would probably have to refactor our AddStreamToZipStream function then, as I don't want to have two competing functionalities. But that should absolutely be doable! I'll look into this later today! Thanks again.

**Comment by JesperSchulz** [comment]
Code has been submitted for code review. Waiting for feedback. I expect to be able to add new code to check-in gates by EOD.

**Comment by JesperSchulz** [comment]
Code was submitted. The pull request was addressed through commit fc011dd252ea8599d007f03bfdd08035d7f75222. If the check-in doesn't live up to your expectations, please reactivate pull request or create a new one with the corrections. Thank you again for your contribution!

**Comment by anzwdev** [comment]
Thank you

**Comment by JesperSchulz** [comment]
I've done some further optimizations, but no changes in functionality :-)
Commit: e511c12e04a425f4e94ebe6fb7d25173af420a0f

**Comment by anzwdev** [comment]
Thank You. 

I remember that my first version of DownloadZip function looked the same as it looks now after your changes, but unfortunatelly it does not work :(. I am getting this error message now: 

> A call to System.IO.Compression.ZipArchive.Dispose failed with this messages: Cannot access a closed Stream

We are getting this error, because disposing of ZipArchive tries to close zip stream that has already been closed by DOWNLOADFROMSTREAM function.

Global MemoryStream that we are using to store ZIP content is managed by ZipArchive object and might not contain all data as part of it might not be saved by ZipArchive yet. We have to close ZipArchive object first to make sure that all zip bytes have been written to the stream. Unfortunatelly closing zip closes memory stream, so we have to create another stream for DOWNLOADFROMSTREAM method. 
I agree, creating TempBlob and storing our zip memorystream buffer there just to create NAV InputStream might not be the best idea, so here is updated function that closes zip archive and creates another memorystream based on closed zip stream buffer:

```
    [External]
    PROCEDURE DownloadZip@6(DialogTitle@1000 : Text;ToFolder@1001 : Text;ToFilter@1002 : Text;ToFile@1003 : Text) : Boolean;
    VAR
      Result@1001 : Boolean;
    BEGIN
      IF DialogTitle = '' THEN
        DialogTitle := DownloadZipFileTxt;
      IF ToFilter = '' THEN
        ToFilter := ZipFileFilterTxt;
      IF ToFile = '' THEN
        ToFile := DefaultZipFileTxt;

      ZipArchive.Dispose;
      ZipMemoryStream := ZipMemoryStream.MemoryStream(ZipMemoryStream.GetBuffer);
      Result := DOWNLOADFROMSTREAM(ZipMemoryStream,DialogTitle,ToFolder,ToFilter,ToFile);
      ZipMemoryStream.Dispose;
      EXIT(Result);
    END;

```

I have a small zip file with a few images inside that I am using to test manually upload and download methods. If you can open images from downloaded zip, it means that it works fine. Here is the function that I am using to test it:

```
    LOCAL PROCEDURE RunManualTest@1000000001();
    VAR
      FileNames@1000000004 : TEMPORARY Record 823;
      TempBlob@1000000005 : TEMPORARY Record 99008535;
      TempBlobInStream@1000000006 : InStream;
      TempBlobOutStream@1000000007 : OutStream;
      UploadedZip@1000000000 : Codeunit 706;
      DownloadedZip@1000000001 : Codeunit 706;
      SourceZipFile@1000000002 : Text;
      DestZipFile@1000000003 : Text;
    BEGIN
      //upload zip
      IF (NOT(UploadedZip.UploadZip('', '', '', SourceZipFile))) THEN
        EXIT;

      //create new zip and copy all files
      UploadedZip.GetEntries(FileNames);
      DownloadedZip.CreateNewZip();
      IF (FileNames.FINDSET()) THEN BEGIN
        REPEAT
          //copy to temp blob to be sure that we are using nav streams
          CLEAR(TempBlob);
          TempBlob.Blob.CREATEOUTSTREAM(TempBlobOutStream);
          UploadedZip.WriteEntryFromZipToOutStream(FileNames.Name, TempBlobOutStream);

          TempBlob.Blob.CREATEINSTREAM(TempBlobInStream);
          //add file from temp blob to the new zip
          DownloadedZip.AddEntryFromStreamToZip(FileNames.Name, TempBlobInStream);
        UNTIL (FileNames.NEXT() = 0);
      END;

      //download new zip
      DownloadedZip.DownloadZip('', '', '', DestZipFile);
    END;

```

**Comment by JesperSchulz** [comment]
Oh! Thanks for testing! My primitive tests here passed, so I assumed it worked fine. Sorry about that! I will of course fix the issue right away, using your suggestion! Stay tuned!

**Comment by JesperSchulz** [comment]
Your fix work, but for some reason my created zip archive is now corrupt in my manual test. Will have to look into that before submitting the code.

**Comment by anzwdev** [comment]
Looks like it was a bad idea to use MemoryStream to keep content of zip in memory. I am changing it to use TempBlob, it seems to be working. Should I paste code here or create another pull request when it is ready and works without any problems?

**Comment by JesperSchulz** [comment]
Feel free to post it where ever you like :-) I'm looking into the issue myself, as I can't quite accept that this doesn't work...

**Comment by anzwdev** [comment]
OK, here is updated version. I've replaced MemoryStream with global ZipTempBlob variable

```
OBJECT Codeunit 706 Zip Stream Wrapper
{
  OBJECT-PROPERTIES
  {
    Date=;
    Time=;
    Version List=;
  }
  PROPERTIES
  {
    OnRun=BEGIN
          END;

  }
  CODE
  {
    VAR
      ZipTempBlob@1000000000 : Record 99008535;
      ZipArchive@1000 : DotNet "'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.IO.Compression.ZipArchive";
      ZipArchiveMode@1004 : DotNet "'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.IO.Compression.ZipArchiveMode";
      SeekOrigin@1002 : DotNet "'mscorlib'.System.IO.SeekOrigin";
      ZipFileFilterTxt@1003 : TextConst '@@@=Only translate "Zip Files" and "All Files";ENU=Zip Files (*.zip)|*.zip|All Files (*.*)|*.*';
      UploadZipFileTxt@1005 : TextConst 'ENU=Upload ZIP file';
      DownloadZipFileTxt@1006 : TextConst 'ENU=Download ZIP file';
      DefaultZipFileTxt@1007 : TextConst 'ENU=Default.zip';

    [External]
    PROCEDURE CreateNewZip@1();
    VAR
      OutputStream@1000000000 : OutStream;
    BEGIN
      CLEAR(ZipTempBlob);
      ZipTempBlob.Blob.CREATEOUTSTREAM(OutputStream);
      ZipArchive := ZipArchive.ZipArchive(OutputStream,ZipArchiveMode.Create);
    END;

    [External]
    PROCEDURE OpenZipFromStream@2(InputStream@1000 : InStream;ZipArchiveModeIsUpdate@1001 : Boolean);
    VAR
      OutputStream@1000000000 : OutStream;
    BEGIN
      CLEAR(ZipTempBlob);
      ZipTempBlob.Blob.CREATEOUTSTREAM(OutputStream);
      COPYSTREAM(OutputStream, InputStream);

      IF ZipArchiveModeIsUpdate THEN
        ZipArchive := ZipArchive.ZipArchive(OutputStream, ZipArchiveMode.Update)
      ELSE
        ZipArchive := ZipArchive.ZipArchive(OutputStream, ZipArchiveMode.Read);
    END;

    [External]
    PROCEDURE UploadZip@3(DialogTitle@1000 : Text;FromFolder@1001 : Text;FromFilter@1002 : Text;FromFile@1003 : Text) : Boolean;
    VAR
      InputStream@1004 : InStream;
    BEGIN
      IF DialogTitle = '' THEN
        DialogTitle := UploadZipFileTxt;
      IF FromFilter = '' THEN
        FromFilter := ZipFileFilterTxt;

      IF UPLOADINTOSTREAM(DialogTitle,FromFolder,FromFilter,FromFile,InputStream) THEN BEGIN
        OpenZipFromStream(InputStream,FALSE);
        EXIT(TRUE);
      END;
    END;

    [External]
    PROCEDURE OpenZipFromTempBlob@4(VAR TempBlob@1000 : Record 99008535;ZipArchiveModeIsUpdate@1002 : Boolean);
    VAR
      InputStream@1001 : InStream;
    BEGIN
      TempBlob.Blob.CREATEINSTREAM(InputStream);
      OpenZipFromStream(InputStream,ZipArchiveModeIsUpdate);
    END;

    [External]
    PROCEDURE SaveZipToStream@5(OutputStream@1000 : OutStream);
    VAR
      InputStream@1000000000 : InStream;
    BEGIN
      ZipArchive.Dispose;
      ZipTempBlob.Blob.CREATEINSTREAM(InputStream);
      COPYSTREAM(OutputStream, InputStream);
      CLEAR(ZipTempBlob);
    END;

    [External]
    PROCEDURE DownloadZip@6(DialogTitle@1000 : Text;ToFolder@1001 : Text;ToFilter@1002 : Text;ToFile@1003 : Text) : Boolean;
    VAR
      Result@1000000002 : Boolean;
      InputStream@1000000000 : InStream;
      OutputStream@1000000001 : OutStream;
    BEGIN
      IF DialogTitle = '' THEN
        DialogTitle := DownloadZipFileTxt;
      IF ToFilter = '' THEN
        ToFilter := ZipFileFilterTxt;
      IF ToFile = '' THEN
        ToFile := DefaultZipFileTxt;

      ZipArchive.Dispose();
      ZipTempBlob.Blob.CREATEINSTREAM(InputStream);
      Result := DOWNLOADFROMSTREAM(InputStream, DialogTitle, ToFolder, ToFilter, ToFile);
      CLEAR(ZipTempBlob);
      EXIT(Result);
    END;

    [External]
    PROCEDURE SaveZipToTempBlob@7(VAR TempBlob@1000 : Record 99008535);
    VAR
      OutputStream@1001 : OutStream;
    BEGIN
      CLEAR(TempBlob);
      TempBlob.Blob.CREATEOUTSTREAM(OutputStream);
      SaveZipToStream(OutputStream);
    END;

    [External]
    PROCEDURE GetEntries@8(VAR TempNameValueBuffer@1000 : TEMPORARY Record 823);
    VAR
      ZipArchiveEntry@1001 : DotNet "'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.IO.Compression.ZipArchiveEntry";
    BEGIN
      FOREACH ZipArchiveEntry IN ZipArchive.Entries DO
        TempNameValueBuffer.AddNewEntry(ZipArchiveEntry.FullName,ZipArchiveEntry.Name);
    END;

    [External]
    PROCEDURE WriteEntryFromZipToOutStream@9(EntryName@1000 : Text;VAR OutputStream@1002 : OutStream);
    VAR
      ZipArchiveEntry@1001 : DotNet "'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.IO.Compression.ZipArchiveEntry";
      ZipArchiveEntryStream@1003 : DotNet "'mscorlib'.System.IO.Stream";
    BEGIN
      ZipArchiveEntry := ZipArchive.GetEntry(EntryName);
      ZipArchiveEntryStream := ZipArchiveEntry.Open;
      ZipArchiveEntryStream.CopyTo(OutputStream);
      ZipArchiveEntryStream.Close;
    END;

    [External]
    PROCEDURE AddEntryFromStreamToZip@10(EntryName@1000 : Text;InputStream@1001 : InStream);
    VAR
      ZipArchiveEntry@1002 : DotNet "'System.IO.Compression, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'.System.IO.Compression.ZipArchiveEntry";
      ZipArchiveEntryStream@1003 : DotNet "'mscorlib'.System.IO.Stream";
    BEGIN
      ZipArchiveEntry := ZipArchive.CreateEntry(EntryName);
      ZipArchiveEntryStream := ZipArchiveEntry.Open;
      COPYSTREAM(ZipArchiveEntryStream,InputStream);
      ZipArchiveEntryStream.Close;
    END;

    BEGIN
    END.
  }
}

```

**Comment by JesperSchulz** [comment]
Great. Thanks! I'll take it for a spin!

**Comment by JesperSchulz** [comment]
That did the trick. I think the problem with MemoryStream is encoding related, but since your pack works nicely, I'll focus my energy on something else ;-) Thanks for all your effort on getting this right.
Changes commited: e9cc5156f4543549a9cdc8a392006d56a6ce2ad5

**Comment by JesperSchulz** [comment]
Btw. the changes should still make it in in time to be shipped with the next update.

**Comment by anzwdev** [comment]
Thank you, and sorry for publishing broken version. 

After rethinking it yesterday evening I think that poblem was caused by me using ZipMemoryStream.GetBuffer() instead of ZipMemoryStream.ToArray() to get content of the zip from closed memory stream. First function returns internal buffer that can be bigger than data saved to the stream while second one returns just saved data, so codeunit was producing zips with some additional bytes at the end of the file. But as solution with TempBlob works fine, I think that it can stay this way.

**Comment by JesperSchulz** [comment]
No worries :-) Now all works fine and no defect code was shipped.
I think we can keep things as they are - NAV style.
Btw., I've got your Signed XML Mgt. ready as well. Will commit it in a few min!
Thanks for the good collaboration on this one.

**Pull request closed without merging**
