### PR TITLE
Decompress stream to xml stream

### PR DESCRIPTION
**Pull request by megel**
https://github.com/Microsoft/cal-open-library/issues/47

### CODE REVIEW

**Comment by JesperSchulz** [comment]
Looks great! I'll get back to you once I've found a new home for your function :-)

**Comment by JesperSchulz** [comment]
Hi Michael! I have to do some refactoring. But since I don't have any test code, I cannot verify if I broke your code. Is there any change you could take my refactored code for a spin? I will create a new pull request, once I'm done. I would then have to ask you to do some manual testing, before we close this pull request. Would that work for you?

**Comment by JesperSchulz** [comment]
Great refactoring and good effort on the test side! You just made my job much simpler :-) I will review and submit your code today.

**Comment by JesperSchulz** [comment]
Do you really need version 2 of the System.Xml.XmlDocument, or can I make it version 4?

**Comment by megel** [comment]
@JesperSchulz, I have fixed a problem with the Memory Stream and added a test codeunit to verify the functionality.

**Comment by megel** [comment]
BTW, Version v4 would be ok (copy/paste from old system)

**Comment by JesperSchulz** [comment]
It's a wrap! Your changes were submitted through pull request #49. The new codeunit should be available through our February update or the upcoming Docker images. Thank you very much for your contribution.

**Pull request closed without merging**
