### PR TITLE
Updates to JwtSecurityTokens and added unit test

### PR DESCRIPTION
**Pull request by gunnargestsson**
Stop using a temporary table and move to JObject

### CODE REVIEW

**Comment by JesperSchulz** [comment]
I can't seem to see the differences. Something is not quite right in this pull request. Could you try again? It's hard to see the differences you want to make.

**Comment by gunnargestsson** [comment]
The last four functions all need to be [External].  I have also removed "Standard Text" as a temporary table (it will not work in all cases) and use JObject instead as the temporary storage for the token claims.

**Comment by JesperSchulz** [comment]
Your suggestions have functions, which have .NET parameters. Those, as you know, cannot be used from V2 extensions. I could not see any other improvements over the code we have in repo. I'm hence closing this pull request without making any changes. Feel free to correct your code and reopen this pull request for further processing.

**Comment by gunnargestsson** [comment]
There are exceptions and this in one of them. This dotnet object has been mapped to AL type and in json management this dotnet type is already external and accessible by Extension V2

Kveðja/Kind regards,
Gunnar Þór Gestsson
________________________________

**Comment by JesperSchulz** [comment]
I see! Case re-opened :-) We will have to re-triage it! Thanks for clarifying!

**Comment by StanislawStempin** [comment]
Keep in mind that new AL types are not really "mapped" to .NET types. You should treat them as completely new AL types. It will not be possible to call the methods from C/AL Open Library that have DotNet types as part of the signature even though similar types might exist in AL.

**Comment by JesperSchulz** [comment]
Based on Stan's comment, I will close the pull request again, as the suggested code changes won't work for V2 extensions. Feel free to refactor and we'll reconsider! Thanks for all your contributions! They are very much appreciated!

**Comment by gunnargestsson** [comment]
I will refactor and submitt another pull request.  But I suggest you take a look at Codeunit 5459 that has external function using DotNet variable.

**Comment by JesperSchulz** [comment]
You're right! We have a lot of external functions in that codeunit with .NET parameters! That is a mistake! I will investigate how those got there. We probably have to make those functions internal or refactor. Thanks for pointing that out!

**Pull request closed without merging**
