### PR TITLE
New function and some made External

### PR DESCRIPTION
**Pull request by gunnargestsson**
New function that will return the mime mapping for a file name.  Path Helper functions made External.

### CODE REVIEW

**Comment by JesperSchulz** [comment]
Something is not quite right. I cannot see, which changes you are proposing. Under "Files Changed", it appears everything has been added, which isn't the case. COD419 is in the repo and there should hence be a limited number of changes. Could you take a look once more? Also, your changes include translations, which should be removed.
Once done, I'll take another look! Thanks!

**Comment by gunnargestsson** [comment]
Well, the COD419.TXT is not in your master branch.  What will happen if you put it there?  Will you then see the changes I suggest?

**Comment by JesperSchulz** [comment]
It's not? I added it earlier today! It should be in master :-)

**Comment by gunnargestsson** [comment]
It is in now.  Decline this pull request, I will create a new one.

**Comment by gunnargestsson** [comment]
I will ask you to add objects to master if I need them before the next pull request.

**Pull request closed without merging**
