### PR TITLE
SignedXml support

### PR DESCRIPTION
**Pull request by anzwdev**
Support for signing and validating signature of signed xml documents using SignedXml .net class. Code is based on msdn examples available here: 

https://msdn.microsoft.com/en-us/library/system.security.cryptography.xml.signedxml(v=vs.110).aspx

### CODE REVIEW

**Comment by JesperSchulz** [comment]
Is this a V1 blocker? Either way, I will look into it soon, but it would be good to know in order to get my prioritization straight.

**Comment by anzwdev** [comment]
I would call it "soft" v1 blocker. We are using it in our V1 extension to check signature of our license xml, so it would be good to have it, but I can comment it out temporary and enable it and resubmit our v2 extension later, when you are ready.

**Comment by JesperSchulz** [comment]
Ok, I will try to get it into the product by EOW then. It might spill over to the beginning of next week though, if high priority blockers or other tasks come in. But the code looks solid, so I'll def. aim for a short turn-around. Thanks once more for another valuable contribution! Much appreciated!

**Comment by JesperSchulz** [comment]
I've completed the work on the Signed XML Mgt. codeunit - which wasn't much of a deal given the great work you've provided.
Please do verify if everything still works as per your expectations and if not, you know the drill ;-)
Thank you for your contribution!

Here is the commit: d5738c75f373f5f18499cc4631611502b127f409

**Comment by anzwdev** [comment]
Everything works great, thank you.

**Comment by JesperSchulz** [comment]
@anzwdev, an issue with your library was reported: https://github.com/Microsoft/cal-open-library/issues/73. Could you maybe take a look?

**Comment by anzwdev** [comment]
I'm going to take a look at it today.

**Comment by JesperSchulz** [comment]
Great! Thanks a lot!

**Pull request closed without merging**
