### PR TITLE
RegEx Split Wrapper

### PR DESCRIPTION
**Pull request by NAVFreak**
This is a wrapper to the dotnet function RegEx.Split(Text, RegExPattern)

### CODE REVIEW

**Comment by JesperSchulz** [comment]
Thank you for your contribution. We will look into it asap. Please do sign the CLA to allow us to proceed.

**Comment by JesperSchulz** [comment]
@NAVFreak, if you could please sign the CLA, then we could continue processing your request. Thanks you very much!

**Comment by NAVFreak** [comment]
Hi,
I know. Unfortunately I had a small setback with my employer. So currently
this is under negotiation. Hopefully this will be sorted out at the end of
the week.

//Marcus

Den 12 mars 2018 14:30 skrev "Jesper Schulz-Wedde" <notifications@github.com

**Comment by JesperSchulz** [comment]
No worries. We'll just wait until the details have been sorted out. Just wanted to make sure, you were aware. There is no rush from our side as such :-)

**Comment by JesperSchulz** [comment]
I can see that the CLA issues were resolved! I didn't get any mail about that and hence missed it :-) I will look into your request next week and get back to you!

**Comment by JesperSchulz** [comment]
Your code was pushed through commit 7369ae886e118db829ec6bacfdf94c43769ea8af. I hope it addresses your needs. Thanks again for your contribution!

**Pull request closed without merging**
