### PR TITLE
New Function to get last String Index

### PR DESCRIPTION
**Pull request by ChristianMuetzePrintVis**
New function LastIndexOfString

This makes use out of "DotNetString.LastIndexOf(Value)"

### CODE REVIEW

**Comment by JesperSchulz** [comment]
Looking into it :-)

**Comment by JesperSchulz** [comment]
I've ported your changes to the master branch. We will be releasing these changes in the next minor of version 15.

**Comment by ChristianMuetzePrintVis** [comment]
Hi Jesper,

can this pull request also be moved to the BC 14 cal-open-library?

// Christian

**Comment by JesperSchulz** [comment]
We are normally not back porting fixes to 14 or lower. What would be your reason to backport it? Maybe we can make an exception if it's good ;-)
Btw. I am not updating this repository any longer, as it has been replaced by [https://github.com/Microsoft/alappextensions](https://github.com/Microsoft/alappextensions). This repo is getting retired, when I have opportunity to do so. As you know, C/AL is a thing of the past - as is the C/AL Open Library. Going forward, please submit modules for System Application!

**Comment by ChristianMuetzePrintVis** [comment]
We aim at "ISV Extension" solution and as we still need BC14 as intermediate step in the upgrade process story I want to lower out footprint and try to make it easier to get to the bc14 while doing the upgrade.

**Comment by JesperSchulz** [comment]
Alright :) I'll see what I can do for you. Have a lovely weekend!

**Comment by JesperSchulz** [comment]
Backported to 14.x and 15.x (to be released with next minor in both).

**Comment by ChristianMuetzePrintVis** [comment]
Thanks Jesper! I own you a beer :)

**Pull request merged**
